/*
 * Personal Finance Management API
 *
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PersonalFinanceManagement.Database.Entities;

namespace PersonalFinanceManagement.Models
{
    /// <summary>
    /// List with support for paging
    /// </summary>
   
    public  class TrPagedList<T>
    {
        public int TotalCount { get; set; }

        public int PageSize { get; set; }

        public int Page { get; set; }

        public int TotalPages { get; set; }

        public SortOrderEnum SortOrder { get; set; }

        public string SortBy { get; set; }

        public List<T> Items { get; set; }
    }
}
